global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-host-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Cấu hình các targets để scrape metrics
scrape_configs:
  # Prometheus tự monitor chính nó
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Node Exporter (metrics của server/host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['domain:443']
    scheme: https
    basic_auth:
      username: 'node_exporter'
      password: 'CHANGE_ME'